apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-api
  labels:
    app: news-api
spec:
  replicas: 2   # number of pods
  selector:
    matchLabels:
      app: news-api
  template:
    metadata:
      labels:
        app: news-api
    spec:
      containers:
        - name: news-api
          image: news-api:latest   # replace with DockerHub or local registry image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
